export {
  UserRole,
  CustomerType,
  AgentAvailability,
  RouteType,
  SurchargeType,
  PaymentType,
  OrderStatus,
  AssignmentType,
  AssignmentStatus,
  AttemptStatus,
  NotificationType,
  NotificationEventType,
  NotificationStatus,
} from "@prisma/client";
